### PR TITLE
Tapping should close the dropdown on touch-devices. closes #80

### LINKED ISSUE #80: Touch Device "tapping" to close the dropdown doesn't work
If a dropdown is open, and you tab on any other element, the dropdown won't close as it does on a `click` based event.

This seems to happen because there is no global listener for `touchstart` as there is for `mousedown`.
See [addon/components/basic-dropdown/content.js](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L35).

Simply adding `this.get('appRoot').addEventListener('touchstart', this.handleRootMouseDown, true);` seems to fix it. If you want I can provide a PR.

### PR DESCRIPTION
**Pull request by Haidy777**
See #80

### CODE REVIEW

**Comment by Haidy777** [comment]
@cibernox Unfortunately the build is failing.
https://travis-ci.org/Haidy777/ember-basic-dropdown/jobs/127170225#L295
Any ideas?

**Comment by ludalex** [comment]
Just tried this on iOS 9.3 w/ Safari and although clicking outside of the element works great, when this version of `ember-basic-dropdown` is used for `emeber-power-select`, clicking _inside_ the dropdown content triggers closing as well, making scrolling lists or selecting the search box impossible.

**Comment by cibernox** [comment]
@ludalex I'd expect [this line](https://github.com/cibernox/ember-basic-dropdown/pull/81/files#diff-557380c41041060ba02fda741c1add2bR106) to take care of that. Can you check why it isn't?

**Comment by ludalex** [comment]
Found another little issue as well, always when used in combination with `ember-power-select`:
Basically clicking on the trigger to close the dropdown content works only twice, then stops functioning.
This happens both on mobile and desktop.

**Comment by ludalex** [comment]
@Haidy777 found out what might be the root cause of these nasty bugs:
bugn x
The `handleRootMouseDown` method is called exponentially on every click, probably due to some event registration bug.

**Comment by Haidy777** [comment]
@ludalex Just checked it with the dev tools (getEventListeners(appRoot)).
Seems like it's not removing the listeners which leads to this exponentially thing. I'm trying to figure it out.

**Comment by Haidy777** [comment]
@ludalex Just updated the commit. The exponentially thing looks like it's fixed. Maybe you could test this again?

**Comment by ludalex** [comment]
I can confirm it's fixed!

File: addon/components/basic-dropdown/content.js [hunk 1]
```diff
@@ -117,5 +142,17 @@ export default WormholeComponent.extend({
       dropdown.removeEventListener('DOMNodeInserted', reposition);
       dropdown.removeEventListener('DOMNodeRemoved', reposition);
     }
+  },
+
+  touchMoveHandler() {
+    const appRoot = this.get('appRoot');
+    if (!this.isDestroying && !this.isDestroyed) {
+      this.hasMoved = true;
+      appRoot.removeEventListener('touchmove', this.touchMoveHandler.bind(this));
```
Comment (cibernox) [inline addon/components/basic-dropdown/content.js]: This is not detaching the event properly. Every time you use `Function.prototype.bind` your are generating a new function, so this event handler you are removing is not the same event handler you attached a few lines below.

You need to, on init, bind it and store it in a propertly, like you already did with `touchStartHandler`

File: addon/components/basic-dropdown/content.js [hunk 2]
```diff
@@ -74,7 +94,12 @@ export default WormholeComponent.extend({
   },
 
   handleRootMouseDown(dropdownContent, e) {
-    let comesFromInside = this.element.parentElement.contains(e.target) || dropdownContent.contains(e.target);
+    if(this.get('hasMoved')){
```
Comment (cibernox) [inline addon/components/basic-dropdown/content.js]: `this.hasMoved` is not a property where we case about observations, so it is save to get/set as any regular property, without using Ember.get/set.

File: addon/components/basic-dropdown/content.js [hunk 3]
```diff
@@ -117,5 +142,17 @@ export default WormholeComponent.extend({
...
+  touchMoveHandler() {
+    const appRoot = this.get('appRoot');
+    if (!this.isDestroying && !this.isDestroyed) {
+      this.hasMoved = true;
+      appRoot.removeEventListener('touchmove', this.touchMoveHandler.bind(this));
+    }
+  },
+
+  touchStartHandler () {
+    this.get('appRoot').addEventListener('touchmove', this.touchMoveHandler.bind(this));
```
Comment (cibernox) [inline addon/components/basic-dropdown/content.js]: I think that this event listener should be attached on the capture phase (pass true as the last argument). Same for removing it.

File: addon/components/basic-dropdown/content.js [hunk 4]
```diff
@@ -47,7 +59,15 @@ export default WormholeComponent.extend({
   willDestroyElement() {
     this._super(...arguments);
     let dropdown = self.window.document.getElementById(this.get('dropdownId'));
-    this.get('appRoot').removeEventListener('mousedown', this.handleRootMouseDown, true);
+    const appRoot = this.get('appRoot');
```
Comment (cibernox) [inline addon/components/basic-dropdown/content.js]: Use let. I will add `ember-suave` soon and it will compain about const being used outside the top-level scope.

File: addon/components/basic-dropdown.js [hunk 5]
```diff
@@ -163,8 +163,10 @@ export default Component.extend({
     if (!this.get('publicAPI.isOpen')) { return; }
     let onClose = this.get('onClose');
     if (onClose && onClose(this.get('publicAPI'), e) === false) { return; }
-    this.set('publicAPI.isOpen', false);
-    this.setProperties({ _verticalPositionClass: null, _horizontalPositionClass: null });
+    if (!this.isDestroying && !this.isDestroyed) {
```
Comment (cibernox) [inline addon/components/basic-dropdown.js]: This is something that intrigues me. I don't see any possible situation where this method can be called once the component is destroyed. Did you find one?

**Comment by cibernox** [comment]
I added a few comments, but at a macro scope it looks good 👍

**Comment by Haidy777** [comment]
Thanks. Just updated the commit. I think I got all your comments covered.

**Comment by cibernox** [comment]
Thanks!
